title: Eclipse Xsemantics
url: "https://www.eclipse.org"
baseurl: /xsemantics

collections:
  staff_members:
    output: false

jekyll-archives:
  enabled:
    - "categories"

exclude: 
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Rakefile"
  - vendor

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"
